executor/batchclient/batch.go
executor/job_manager.go
executor/job_manager_test.go

add polling for task updates
* start a goroutine when creating a new job
* stop polling if the job status becomes Cancelled, Failed, Succeeded
* restarts will cause polling to stop; okay to deal with this right now
we need to eventually ECS task event listener via SNS/SQS
* don't update the DB if no task.Status has changed

Add job status polling

---

executor/batchclient/batch_test.go
executor/job_manager.go

https://clever.atlassian.net/browse/INFRA-2299
Also modifies the job status change logic, so that we only save the job
to the store if its status has changed.

executor: log job create, cancel, and status change

---

Dockerfile
executor/job_manager.go
glide.lock
glide.yaml
kvconfig.yml
main.go

Add log-routing to be able to set alerts on workflows. Don't really know yet if we should send the `id` as a dimension, but right now the dimensionality for it is pretty low so why not.

Add kayvee-go based log-routing

---

executor/job_manager.go
executor/job_manager_test.go
gen-go/models/job_input.go
gen-js/package.json
glide.lock
handler.go
resources/tasks.go
resources/workflows.go
swagger.yml

- providing a namespace to the CreateJob endpoint performs a lookup in
the StateResource table to lookup the BatchJobDefinitionARN.
- leaving the namespace blank (== "") mirrors the current behavior where
it is expected that the Workflow.State.Resource is set to a valid ARN.
- Another minor change here is to add StateResource to the `Task` model.
This will allow us to lookup the JobDefinitionARN used to create the
task.
----------------

Dynamic jobdefinition lookup

---

executor/job_manager.go

this allows us to keep the {namespace--app} format without making
namespace a required arg

allow namespace to be "" and use `default` in task

---

executor/job_manager.go
executor/job_manager_test.go

When AWS Batch hits a `container-pull` or `container-start` issue it immediately marks all tasks as `Failed` without `Starting`. This is marked as `TaskStatusAborted` in `workflow-manager`.
This change adds `Job.Status` handling for all tasks getting marked as `TaskStatusAborted` or if any task is `TaskStausAborted` outside of `workflow-manager` (e.g. through the AWS console or CLI).

handle TaskStatusAborted and TaskStatusUserAborted

---

executor/batchclient/batch.go
executor/batchclient/batch_test.go

See https://clever.atlassian.net/browse/INFRA-2439
This change simply replaces the `ContainerInstanceArn` with the `TaskArn` for a job's container. I'm not convinced this value will be present, so I'd appreciate advice about how to test before deploying.

Use TaskArn rather than Container Instance ARN

---

circle.yml

Hooks workflow manager up to our CD system. Will send a prompt to Slack
to confirm deployments.

circle: enable dapple 'confirm-then-deploy'

---

launch/workflow-manager.yml
main.go
store/dynamodb/dynamodb_store.go
store/dynamodb/dynamodb_store_test.go

This is so we can read from the prod definitions and state resources tables in local/staging, but continue to write to the staging workflows table.
Config added in https://github.com/Clever/ark-config/pull/604

Split out config for the various dynamo tables.

---

executor/workflow_manager.go
glide.lock
glide.yaml
main.go
store/dynamodb/dynamodb_store.go
store/dynamodb/dynamodb_store_test.go
store/dynamodb/workflow.go
store/memory/memory_store.go
store/memory/memory_store_test.go
store/store.go
store/tests/tests.go

https://clever.atlassian.net/browse/INFRA-2300
Before this change, workflow-manager would initiate a goroutine on workflow submission that monitored the workflow for updates. This introduced state to workflow-manager that is lost on restart, similar to what we have today with gearman-admin.
This PR removes the polling loop on individual workflows and replaces it with a polling loop that is running constantly looking for workflows in a pending state. When it finds one, it locks it, and then attempts to perform an update on it.
There are roughly three parts to this change, broken down into three commits:
1) add a `GetPendingWorkflows` method to the store interface that returns workflows that are in a queued or running state.
2) add a `LockWorkflow` and `UnlockWorkflow` that lets you lock a …

remove polling loop on individual workflows

---

executor/workflow_manager_test.go
gen-go/models/job.go
gen-js/package.json
handler.go
resources/jobs.go
swagger.yml

This adds `input` and `output` fields to the `Job` model used in API responses.
Exposing additional fields on the internal `Job` model and using that in the conversion to WAG model.
Implementation work is WIP in an upcoming PR. Just splitting these up for ease of review.

Expose per-job inputs and outputs

---

executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go

Use double dash `--` to separate the different components of state machine names and resource names

tweak naming of state machines / resources

---

gen-js/README.md
gen-js/index.js
handler.go
store/dynamodb/dynamodb_store.go
store/dynamodb/page_key.go
store/dynamodb/page_key_test.go
store/dynamodb/workflow.go
store/memory/memory_store.go
store/store.go
store/tests/tests.go
swagger.yml

Adds support for sorting/filtering/pagination to the `getWorkflows` API.
Uses a new secondary index on the concatenated workflow definition name and status: https://github.com/Clever/infra/pull/641

Filter/pagination implementation for getWorkflows API

---

executor/workflow_manager_batch_test.go
handler.go
handler_test.go
resources/kitchensink.go
resources/workflow_definitions.go

No external API changes. Seems like this just slipped past the mega-schema migration.

use req.Manager in create/update WorkflowDefinition

---

executor/workflow_manager_sfn.go

Since the API exposes the input as a JSON string, skip the unmarshalling step and pass the input through directly.
Was previously generating empty strings.

Fix job input propagation for sfn manager.

---

executor/workflow_manager_sfn.go

Workflow-id is now added as property as `$execution-name`.  It's used by sfncli and kayvee to make it easier to correlate logs from a workflow across many workers.
Also added validation to ensure that the worker input is a json object.
Related: https://github.com/Clever/sfncli/pull/4
Jira: https://clever.atlassian.net/browse/INFRA-2553, https://clever.atlassian.net/browse/INFRA-2526

Workflow-id is now added to the jobs before they're submitted

---

executor/workflow_manager_sfn.go

When an `ExecutionAborted` event is encountered, mark the job as `aborted_by_user` (i.e. cancelled).
e.g. https://us-west-2.console.aws.amazon.com/states/home?region=us-west-2#/executions/details/arn:aws:states:us-west-2:589690932525:execution:mp-sfn--multiverse-multiverse-workflow-definition--1--development:3ee31208-f05a-45da-a537-78f403d66359

Handle ExecutionAborted and mark jobs as aborted_by_user accordingly.

---

resources/workflow_definitions.go
resources/workflow_definitions_test.go

Found a bug in the task ordering logic for AWS Batch. Added a simple test to ensure that basic linear things are ordered.

fix ordering error in OrderedStates

---

launch/workflow-manager.yml

While running load tests we've been seeing spikes in CPU and memory way above the currently requested resources. This will ensure that we have a better sense of where we land.

a little more resources

---

executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go

https://clever.atlassian.net/browse/INFRA-2557
Added tests, also tested manually by deleting the activity for `raf--cil-reliability-dashboard` and attempting to submit a workflow for it. Checked the status and it now looks like this:
```
$ ark wfbeta status -e raf -w 49b4f429-8f3c-4413-b1dd-21355e943386
workflow ID:			49b4f429-8f3c-4413-b1dd-21355e943386
workflow Status:		failed
workflow Input:		{}
WorkflowDefinition Name:		cil-reliability-dashboard:master
WorkflowDefinition Version:	4
workflow Namespace:		raf
workflow Queue:		development
TASK ID    STATE    ECS TASK ID    STATUS                  STATUS REASON
2          start                   failed                  State resource does not exist
```

detect if activity doesn't exist

---

executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go

https://clever.atlassian.net/browse/INFRA-2575
https://clever.atlassian.net/browse/INFRA-2547
here's an example execution that had a state retry once: https://us-west-2.console.aws.amazon.com/states/home?region=us-west-2#/executions/details/arn:aws:states:us-west-2:589690932525:execution:raf--cil-reliability-dashboard-master--4--start:3956fc73-d95a-43f6-9984-22f5e5f07ffd
before, workflow-manager would return an empty "attempts" array, only reporting the successful job run: 
```
curl https://clever-dev--workflow-manager.int.clever.com/workflows/3956fc73-d95a-43f6-9984-22f5e5f07ffd
{
"createdAt": "2017-10-09T22:31:02.497Z",
"id": "3956fc73-d95a-43f6-9984-22f5e5f07ffd",
"input": "{}",
"jobs": [
{
"attempts": null,
"createdAt": "2017-10-09T22:31:02.000Z",
"id": "2",
"input": …
```

capture job attempts and associate events with jobs via previous / current event IDs

---

executor/sfncache/sfn.go
executor/sfncache/sfn_test.go
glide.lock
glide.yaml
main.go

https://clever.atlassian.net/browse/INFRA-2580
AWS rate limits DescribeStateMachine with a token bucket that refills at a rate of 1 per second. We will hit this pretty quickly under normal use.
This PR caches calls to that API method using an LRU cache w/ space for 1000 state machines. State machines are immutable and not that big, so caching this method doesn't present a huge risk.

cache DescribeStateMachine calls

---

.github/pull_request_template.md
circle.yml
swagger.yml

Everytime `make generate` is run the `VERSION` file is updated with the swagger client version which can then be used by the `github-release` script to automatically tag the release. 
- [NA] Update swagger.yml version
- [ * ] Run "make generate"

generate VERSION for github-release on make generate

---

executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go

Make sure we update the last-seen job when we encounter an execution event (which wouldn't have a `PreviousEventId` value).
**Testing:**
- Confirmed that this properly sets the status and status reason on the last job if the execution fails. e.g. [hubble/87dc43fd-fc1b-4ccb-bdf5-acb8cc4b106c](https://clever-dev--hubble.int.clever.com/multiverse:master/workflows/w/87dc43fd-fc1b-4ccb-bdf5-acb8cc4b106c/jobs)
- (Compare with [hubble/28c60677-3da2-4199-bb6a-85e198c67ab4](https://clever-dev--hubble.int.clever.com/multiverse:master/workflows/apps/5674595f800a410001000004/w/28c60677-3da2-4199-bb6a-85e198c67ab4/jobs))
**Rollout:**

Fix job update logic for execution-level events

---

executor/log_helpers_test.go
executor/workflow_manager.go
executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go
kvconfig.yml

* Add workflow-id in logs for polling failures when possible
* send poll-for-pending-workflows errors to signalfx
* if lastUpdated < 5 minutes and we hit ExecutionNotFound, then don't
fail:
| This delay would not work as intended if there is a large backlog in
our update workflow polling, but in that case we should not have a
consistency issue anyways.
NOTE: I'm not a 100% sure that the issue where we saw a
ExecutionNotFound error for an execution that later existed was due to a
quick status check. These changes should also allow us to setup alerts
so that if we see ExecutionNotFound errors we can investigate right
away.
- [ N/A ] Update swagger.yml version
- [ N/A ] Run "make generate"

On ExecutionNotFound wait 5 minutes before failing

---

executor/log_helpers.go
executor/log_helpers_test.go
executor/sfncache/sfn.go
executor/sfncounter/cumulativebucket.go
executor/sfncounter/sfn.go
executor/sfncounter/sfn_test.go
executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go
glide.lock
glide.yaml
kvconfig.yml
main.go

Adds an implementation of sfniface.SFNAPI that intercepts calls to `GetExecutionHistoryPagesWithContext` and increments a counter. Logs the value of this counter and routes it to signalfx.
This should let us monitor our total request rate to this method, and also give us a good idea of how effective our strategies are around controlling our request rate.
It might also serve as template for doing this elsewhere in our code where we hit AWS API limits (I'm looking at you, ecs-metrics 😜 )

log / route count of calls to GetExecutionHistory

---

executor/workflow_manager.go
executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go
handler.go

This PR changes the update loop to only update the "summary" portion of the workflow object, eliminating calls to `DescribeExecutionHistory` in that loop.
In my mind this PR is an intermediate step... I think in the long run the workflow object should probably split in two and have one object that represents a summary and another that represents a history (basically the same split that AWS has in their data model between an Execution and an ExecutionHistory).

separate workflow summary update from history update

---

executor/log_helpers.go
executor/log_helpers_test.go
executor/sfncounter/sfn.go
executor/sfncounter/sfn_test.go
executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go
kvconfig.yml
main.go

https://clever.atlassian.net/browse/INFRA-2620
Adds a counter for DescribeExecution calls. This API method has a limit of 2 per second, and is now the only method called in the update loop. We should monitor it. I've also requested an increase to 50 per second with AWS

add counter for describe execution calls

---

executor/workflow_manager_sfn.go

Would like to include details about which branch of the workflow was taken, so that it's clearer to users (and the client doesn't have to extrapolate).
**Basically go from this (no job data past last Task):**
https://clever-dev--hubble.int.clever.com/multiverse:master/workflows/w/77e8b1f0-a2e7-4b28-8794-438ce8a0cb23/jobs
**to this (Choice and Succeed step details included):**
https://clever-dev--hubble.int.clever.com/multiverse:master/workflows/w/1ec091c2-3e88-4087-8ffa-e4f9c47c6851/jobs

[Proposal] Start parsing details for Choice and Succeed tasks for client visibility

---

executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go

From https://states-language.net/spec.html#error-names
> The reserved name “States.ALL” in a Retrier’s “ErrorEquals” field is a
wild-card and matches any Error Name. *Such a value MUST appear alone in
the “ErrorEquals” array and MUST appear in the last Retrier in the
“Retry” array.*
- [ na ] Update swagger.yml version
- [ na ] Run "make generate"

Prepend defaultRetry to conform to spec

---

executor/log_helpers.go
executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go
store/dynamodb/dynamodb_store.go
store/memory/memory_store.go
store/store.go
store/tests/tests.go

Progress on INFRA-2607: Job history occasionally missing from workflows
I was able to reproduce a case where we failed to startExecution due to rate limiting and then status updates kept failing since we could not find the execution. This change attempts to make `CreateWorkflow` to be more transactional. 
TODO: add tests for this condition. ✅ 
- [ na ] Update swagger.yml version
- [ na ] Run "make generate"

Remove workflow sfn create fail

---

executor/workflow_manager_sfn.go

Basically, don't set `Job.StartedAt` until the job actually starts, so we have an idea of time waiting in queue for historical jobs.

Fix job start date to be when the activity was started.

---

docs/definitions.md
docs/overview.md
gen-go/models/start_workflow_request.go
gen-js/package.json
handler.go
swagger.yml

go-swagger wasn't doing the default for us (see https://github.com/Clever/workflow-manager/blob/18a48402b27c3b73804eb58d6edf4b29e7ff01b6/gen-go/models/start_workflow_request.go)

Fix default queue

---

executor/workflow_manager_sfn.go

Minor bug was causing the attempts array to contain only one previous attempt.

Persist all previous job attempts when creating new ones.

---

executor/workflow_manager_sfn.go

Previously, we only set this flag if a user manually submitted it. In
practice, we want a simple query for all "unresolved" workflows versus
"resolved" ones.
- Unresolved: queued, running, failed (but not yet investigated)
- Resolved: succeeded, cancelled, failed (and investigated)
This change auto-resolves succeeded and cancelled, and leaves it up to
the user to manually resolve failed workflows.

Set ResolvedByUser if workflow succeeded/cancelled

---

Makefile

In Dev, this helps ensure that we don't persist data in two different
formats in DynamoDB. Otherwise, it's easy to mistakenly write data like
```
LastUpdated= 2017-10-20T17:42:31.394932656Z
LastUpdated= 2017-10-04T20:09:24.964107-07:00
```
If code isn't written carefully, this can lead to unexpected errors when
handling / sorting dates.
After this change, we'll ensure all dates are written in the first
format.
- [n/a ] Update swagger.yml version
- [n/a] Run "make generate"

Use UTC timezone when running locally

---

executor/workflow_manager_sfn.go

Followup to https://github.com/Clever/workflow-manager/pull/105
Previously, if a workflow was cancelled, it never got the resolvedByUser attribute set to true. We were attempting to update this bool during `UpdateWorkflowSummary`, but this function exits early if a `WorkflowIsDone` ... which includes being cancelled.
https://github.com/Clever/workflow-manager/blob/4fd44aeb0edeb7d46019cb5e355cdc83299d3533/executor/workflow_manager_sfn.go#L347
We now update it within `CancelWorkflow`

Set `ResolvedByUser = true` within `CancelWorkflow`

---

executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go
store/dynamodb/dynamodb_store.go

https://clever.atlassian.net/browse/INFRA-2703
Previously, we allowed cancelling failed workflows as a workaround for
"resolving". We cancelled a failed job in order to manually acknowledge
that we were done investigating that job.
We recently added the concept ResolvedByUser in workflow-manager:
https://github.com/Clever/workflow-manager/pull/101
This means we can remove the overloaded idea of cancelling failed jobs,
and instead mark them as ResolvedByUser.

Disallow cancelling failed workflows

---

Gopkg.lock
Gopkg.toml

We needed it to be compatible with other things. :sigh:
FYI, hard-coding a specific version, rather than a branch.
No changes to generated code, so I'm just going to go ahead and merge.

Force gomock 1.0.0 instead of master.

---

Dockerfile
Makefile

Context: https://github.com/Clever/dev-handbook/pull/103/
When we run `ark start --local`, it's not necessary to do a CGO build.
We only need CGO when building the go binary to put into an Alpine linux Docker image.
Doing a non-CGO build locally can decrease build times drastically, ~10x faster
_NOTE_: Assuming a passing build, unless you reject the PR, I will auto-merge after ~1 day.

Optimize `make build` for faster local builds

---

Gopkg.lock
docs/definitions.md
docs/overview.md
executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go
gen-go/models/state_resource_type.go
gen-js/package.json
swagger.yml

https://clever.atlassian.net/browse/INFRA-2781
Adds support for interpreting workflow definitions that contain lambda resources, e.g.
```yml
manager: step-functions
name: cil-reliability-dashboard
stateMachine:
Version: '1.0'
StartAt: start
TimeoutSeconds: 14400 # 4 hours
States:
start:
Type: Task
Resource: lambda:cil-reliability-dashboard # <--- 
TimeoutSeconds: 3600  # 1h
HeartbeatSeconds: 30
Retry:
- MaxAttempts: 2
ErrorEquals: [ "States.ALL" ]
End: true
```

add lambda support

---

README.md
main.go
resources/workflows.go
store/dynamodb/dynamodb_store.go
store/tests/tests.go

- DynamoDB does not like items > 400KB. 
Therefore we can return a large workflow but not save it
Additional things we could do here:
- limit by number of jobs. This would mean we don't have to retry
- exit out of UpdateWorkflowDetail early for large workflows. We should have some kind of limit to prevent against Hubble reloading a large workflow too often, since it hits our AWS limits hard. 
- binary encode jobs array so that we can save jobs in ddb (I don't see a strong reason for this right now)

don't save Jobs for very large workflows

---

Gopkg.lock
Makefile
executor/log_helpers.go
executor/log_helpers_test.go
executor/workflow_manager.go
executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go
kvconfig.yml
launch/workflow-manager.yml
main.go
store/dynamodb/dynamodb_store.go
store/memory/memory_store.go
store/store.go
store/tests/tests.go

JIRA: https://clever.atlassian.net/browse/INFRA-2829
This replaces polling dynamodb for updates (lots of calls against DynamoDB: looking up workflows, locking, and updating workflows) with a queue-based approach (puts workflows to update in a queue, no need for locking).
See mini-spec for more details: https://docs.google.com/document/d/1ghjxiImZYRN2ub233okATn2hG1McKhFm9yvm1rL_kPw/edit?ts=5a99edca#
I've tested locally and seems to work smoothly.
Considerations:
- I want to improve unit testing a little more
- Would it be worth abstracting the queue further? Lots of folks have made small abstractions around SQS that would help minimize the need to pass around config like delay duration, queue URL, etc (example: https://github.com/h2ik/go-sqs-poller)
--

Update Loop using SQS

---

executor/workflow_manager.go

Previously it was logging the update loop lag *after* being updated 🤕 
This fixes it to computing the lag *before* running `UpdateWorkflowSummary`

Bugfix when logging update loop lag

---

Gopkg.lock
executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go

This will make sure we don't just keep polling while the ALB has timed out. 
Also going to add a task for next sprint to support handler level timeout context

don't pull workflow history for more than a minute

---

executor/workflow_manager.go
executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go
handler.go
main.go
store/dynamodb/dynamodb_store.go
store/dynamodb/dynamodb_store_test.go
store/memory/memory_store.go
store/store.go
store/tests/tests.go

- use `http.TimeoutHandler` to send a 5XX response after a 5s timeout
- use custom middleware to cancel the `http.Request`'s context object
- pass request context to AWS API calls
end effect should be:
- clients of workflow manager will receive a 5xx after 5s
- the workflow-manager goroutine for a timed-out request will stop making AWS requests

add server-level timeout

---

Gopkg.lock
Gopkg.toml
docs/overview.md
gen-go/server/db/dynamodb/dynamodb_test.go
gen-js/package.json
swagger.yml

Since it's causing some trouble with HM dependency vendoring. I ran into a problem before where not having the latest mock version would error, but I can't get it to reproduce now:
https://circleci.com/gh/Clever/il-user-service/90?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
Since `mock` is a dev dependency, it should not affect production to use the master build.
I think it was initially locked because of some HM vendoring problems (https://github.com/Clever/workflow-manager/pull/117/files) but I was able to successfully run `make install_deps` after vendoring this specific branch onto HM, so this should work.

use mock from master

---

.circleci/config.yml

Since `workflow-manager` is a WAG service, this PR:
- uses the version of the base docker image with node (by SHA, to lock in exact versions)
- unrelated, remvoes some uneccessary line breaks

[INFRA-3134] workflow-manager is wag so needs node

---

executor/workflow_manager.go

We've just got the bucket size increased for `DescribeExecution` and therefore we should be able to handle more messages per batch. Increasing the batch size should also allow us to handle more active executions with a lower workflow-manager container count. This is helpful since we don't have much CPU usage per container. 
Ideally long term we want to be able to control the rate via environment variable.

Rate limit is increased; Pull more messages

---

executor/workflow_manager.go

Reverts Clever/workflow-manager#144
This did not work since `ReceiveMessage` has a max value of 10
> The maximum number of messages to return. Amazon SQS never returns more messages than this value (however, fewer messages might be returned). Valid values: 1 to 10. Default: 1. - [docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html)

Revert "Rate limit is increased; Pull more messages"

---

Gopkg.lock
Gopkg.toml
Makefile
executor/log_helpers.go
gen-go/client/client.go
gen-go/models/inputs.go
gen-go/server/db/dynamodb/dynamodb.go
gen-go/server/db/dynamodb/workflowdefinition.go
gen-go/server/db/interface.go
gen-go/server/db/tests/tests.go
gen-go/server/handlers.go
gen-js/README.md
gen-js/index.js
gen-js/package.json
store/dynamodb/dynamodb_store.go
store/memory/memory_store.go
store/tests/tests.go

Currently, going to this URL will crash workflow-manager: https://production--workflow-manager.int.clever.com/workflow-definitions/alskdjf/0
This PR is trying to fix that bug
- Upgraded to the latest WAG
- Removed references to WAG DB code.  The latest WAG had backwards incompatible changes to the DB package.  The only function that used this code was `GetWorkflowDefinition`.  It now uses the dynamo library directly.
- Changed some log levels to Trace
cc @mohit

Fix 404 crash

---

Gopkg.toml
handler.go
handler_test.go
store/dynamodb/dynamodb_store.go
store/memory/memory_store.go
store/tests/tests.go

Workflow-manager now allows people filter to filter by `status` is `resolvedByUser`.  It uses a [Filter Query](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html#Query.FilterExpression) to ensure the query remain performant.  Filter Queries filter after they query is completed.  In other words:
> a Query will consume the same amount of read capacity, regardless of whether a filter expression is present.
cc @mohit

The /workflows endpoint can now filter by both status and resolvedByUser

---

Gopkg.lock
Gopkg.toml
docs/overview.md
gen-js/package.json
swagger.yml

Uses new version of `kayvee-go` to avoid container crashes from a race condition in that library. The `kayvee-go` code change (https://github.com/Clever/kayvee-go/pull/71) to avoid the race condition got released as version 6.15.0.

update kayvee-go version to stop crashes

---

main.go

Hubble and ark are seeing timeouts from workflows.  This is hopefully a quick fix

Increased global timeout to 5 seconds

---

main.go

Reverts Clever/workflow-manager#154
Root cause of hitting the 5s timeout was the default dynamodb client retry strategy of 10 retries, with (50ms * 2^n) backoff after the nth try: https://github.com/aws/aws-sdk-go/blob/v1.13.0/service/dynamodb/customizations.go This meant we could potentially wait up to (2^9 + 2^8 + ... 2)*50 milliseconds or ~50 seconds for retries to complete. @toddobryan-clever changed the max number of retries to 2 and the p99 immediately dropped back down to reasonable levels.

Revert "Increased global timeout to 5 seconds"

---

executor/workflow_manager.go
resources/workflows.go

I took a peek at the SQS queue and found some workflows that were
really old, but still in the queue. Turns out these workflows were
finished, but had jobs that were still "in progress". This would
happen if someone loaded it in hubble (triggering an update of the
jobs array), but then never again loaded it.
The workflow.Jobs array is kind of a dumpster fire right now, so I'm
not entirely surprised by this bug... in the long run I think it
should be removed from the workflow object.
Here's an example workflow with the problem:
id: 53332426-43c8-4746-bcdb-47f8f3f545a8
discovered it by polling the SQS queue in the console and noticing that it was showing up more than once
looked it up in dynamo and saw that it was started / finished two weeks ago:
Note the final job in the jobs array shows …

update loop should not look at jobs array when deciding to requeue

---

Gopkg.lock

Process-metrics had a type-o ([`guage`](https://production--haproxy-logs.int.clever.com/_plugin/kibana/#/visualize/create?indexPattern=%5Blogs-%5DYYYY-MM-DD&type=histogram&_a=(filters:!(),linked:!f,query:(query_string:(analyze_wildcard:!t,lowercase_expanded_terms:!f,query:'type:guage')),vis:(aggs:!((id:'3',params:(field:container_app,orderBy:'2',size:20),schema:segment,type:terms),(id:'2',schema:metric,type:count)),type:histogram))&_g=(refreshInterval:(display:Off,pause:!f,section:0,value:0),time:(from:now-1w,mode:relative,to:now))) vs `gauge`) which causes errors in kinesis-alerts-consumer.

Updated process-metrics to fix metrics bug

---

Gopkg.lock
Gopkg.toml
docs/overview.md
gen-go/client/doer.go
gen-go/client/mock_client.go
gen-go/server/db/dynamodb/workflowdefinition.go
gen-go/server/db/tests/tests.go
gen-go/server/mock_controller.go
gen-go/server/router.go
gen-js/README.md
gen-js/index.js
gen-js/package.json
package-lock.json
swagger.yml

This is causing problems in apps that depend on both App Service and
Workflow Manager.
App Service depends on the latest stable release of
`github.com/golang/mock` which is currently `1.2.0`. Workflow Manger
depends on an even newer version, `master`.
The latest stable release (`1.2.0`) will satisfy the requirements of
App Service, Workflow Manager, and all of the apps that depend on both
Workflow Manager and App Service.
Solving failure: No versions of github.com/Clever/workflow-manager met constraints:
0.9.3: Could not introduce github.com/Clever/workflow-manager
(from git@github.com:Clever/workflow-manager.git)@0.9.3,
as it has a dependency on github.com/golang/mock with constraint
master, which has no overlap with the following existing constraints:
^1.2.0 from …

Relax go mock version requirement

---

executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go

trying to dig into failed `startWorkflow` requests for specific workflow IDs, so adding the ID to request-finished logs

add workflow id to log context for request-finished

---

docs/definitions.md
docs/overview.md
executor/sfn_events.go
executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go
gen-go/models/workflow_summary.go
gen-js/package.json
swagger.yml

The hubble/repairs page is slow to load when there are a large number of active workflows. The reason for the slowness is that it iterates through every active workflow and loads the full workflow history for each one. We are in the process of modifying Hubble to query Elasticsearch for active and recent workflows instead of using workflow-manager, and we are also exploring the possibility of querying Elasticsearch for failed workflows. This change introduces a new method that fetches the most recent events in the state machine's execution history, and stores the last Job info in the `WorkflowSummary`. The new method shares a lot of logic with https://github.com/Clever/workflow-manager/blob/f0f8abee201526cbe7f51ee93fcb41dbf6d0cd27/executor/workflow_manager_sfn.go#L372, and the main …

workflow last job info

---

executor/workflow_manager.go

Log any errors that occur when attempting to put new workflows in the update loop. This change is part of an investigation into mysterious 503 errors which happen within `CreateWorkflow`. The errors seem to happen with workflows that never get updated which supports @meliaj 's theory that they are the root cause of the forever queued workflows.

log sqs sendMessage errors when creating pending workflows

---

executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go

This is sort of a follow up to https://github.com/Clever/workflow-manager/pull/179. There are many workflows that create over 100 events, so I think we could reduce the number of calls to `GetExecutionHistory` if we bump the results per page from the default of 100 to 200.
https://docs.aws.amazon.com/step-functions/latest/apireference/API_GetExecutionHistory.html#API_GetExecutionHistory_RequestSyntax
I tested this in staging by looking at some workflow histories.

bump execution history events per page

---

docs/overview.md
executor/workflow_manager.go
executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go
gen-js/index.d.ts
gen-js/package.json
handler.go
main.go
swagger.yml

This branch adds tracing to workflow manager (in addition to the baseline tracing from wag). It uses the same `opentracing-contrib/aws-sdk-go` to put some coarse tracing around SFN and SQS calls, uses some handwritten spans for elasticsearch, and throws in a couple of spans around some other things for good measure. In order to make this work well, I needed to pass around a context in a few more places than already had it. 
* In one place, I changed an existing log call to use a different key name - from "wf-id" to "workflow-id" which is used in other places within this library and elsewhere. I don't think this breaks anything, but it would make searching for logs across a bit weird. It can still be done with `wf-id:<ID> OR workflow-id:<ID>`, though, so I think I'd rather have it cleaner …

Workflow Manager Tracing

---

executor/workflow_manager.go
main.go

After looking at the source for `http.TimeoutHandler`, I think it does everything out custom little middleware gizmo does, so we don't need our custom one. Also, add some tagging to `updateWorkflow` with the result of the operation, so it can be filtered more easily.

Tracing cleanup

---

executor/workflow_manager.go
executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go
gen-go/server/router.go

Jira reference: https://clever.atlassian.net/browse/INFRA-3482
This way, every workflow that was started will be picked up by an update loop, getting around the problem of a workflow not being updated because something went wrong before the SQS message was sent. See the discussion on Jira for more info.

Infra 3428 startworkflow failures

---

executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go

Previously wfm only tagged on creation of state machines. This PR tags state machines regardless of whether it is a new or existing state machine. This will improve coverage of tags

tag state machines, take two

---

executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go

Reverts Clever/workflow-manager#217
we're going to have to backfill tagging existing state machines, we hit AWS rate limits

Revert "tag state machines, take two"

---

Gopkg.toml

dep does not support module suffixes (at the moment). This package was
preventing `make install_deps` from running.

Ignore es/v6/estransport when installing dependencies

---

docs/definitions.md
docs/overview.md
embedded/embedded.go
gen-go/models/start_workflow_request.go
gen-go/server/router.go
gen-js/index.d.ts
gen-js/index.js
gen-js/package.json
swagger.yml

This PR attempts to address the problem that embedded `workflow-manager` execution names do not encode human readable information. The approach we use here is to allow clients to pass in a `suffix` we append and trim to be within step functions limits
I don't think we're making any breaking changes by switching away from a UUID. That field isn't actually used in the embedded pathway at all.
My main concern is in regard to Step Functions consistency: https://docs.aws.amazon.com/step-functions/latest/dg/concepts-read-consistency.html
right now we have a 5s delay between `Update` and `StartExecution`

Embedded allow setting execution name

---

docs/overview.md
gen-js/package.json
store/dynamodb/dynamodb_store.go
swagger.yml

From https://docs.aws.amazon.com/sdk-for-go/api/service/dynamodb/#ScanOutput
```
// An array of item attributes that match the scan criteria. Each element in
// this array consists of an attribute name and the value for that attribute.
Items []map[string]*AttributeValue `type:"list"`
```

items is array not map

---

handler.go
handler_test.go

This is a second attempt at https://github.com/Clever/workflow-manager/pull/208
Given a workflow ID and the name of a workflow state to start from, `resumeWorkflowByID` creates a new workflow that begins execution from the `StartAt` state and uses the input to that state from the original workflow. The new workflow is then linked to the original as a retry. The way that `resumeWorkflowByID` finds the workflow input that it needs is by searching through the original workflow's `jobs` array. It relies on `jobs` being populated ahead of time, however `jobs` is not populated automatically like other workflow fields are. In order for `jobs` to exist for a workflow, `getWorkflowByID` must be called before `resumeWorkflowByID` is called, otherwise `jobs` will be `nil` and `resumeWorkflowByID` …

Use the input from lastJob when it's available

---

embedded/embedded.go
embedded/poll.go

Embedded WFM is an awesome abstraction to leverage running finite state machines from one place. One limitation the current implementation has is each `Resource` can have `at max 1` execution at any given time. This limitation eventually becomes a bottleneck if there is a single embedded wfm servicing a production load.
We attempt to resolve this by adding a configurable parallelism, tracking concurrency, and invoking resource calls with goroutines.

Embedded WFM: allow parallel executions for a resource

---

.github/CODEOWNERS
executor/workflow_manager_sfn.go

We're seeing [some panics](https://dev-infra--haproxy-logs.int.clever.com/_plugin/kibana/app/kibana#/discover?_a=(columns:!(rawlog),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'77a51410-ffde-11e8-8a0a-ada6ce1be4ca',key:path,negate:!t,params:(query:%2F_health),type:phrase,value:%2F_health),query:(match:(path:(query:%2F_health,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'77a51410-ffde-11e8-8a0a-ada6ce1be4ca',key:title,negate:!t,params:(query:'please%20set%20TRACING_ACCESS_TOKEN%20%26%20TRACING_INGEST_URL%20to%20enable%20tracing'),type:phrase,value:'please%20set%20TRACING_ACCESS_TOKEN%20%26%20TRACING_INGEST_URL%20to%20enable%20tracing'),query:(match:(title:(query:'please%20set%20TRACING_ACCESS_TOKEN%20%26%20TRACING_INGEST_URL%20to%20en …

Prevent out of range panic

---

.github/pull_request_template.md
Gopkg.lock
Gopkg.toml
docs/definitions.md
executor/sfnconventions/sfnconventions.go
executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go
gen-go/models/s_l_state.go
gen-go/models/state_resource_type.go
gen-js/index.d.ts
package-lock.json
swagger.yml

https://clever.atlassian.net/browse/INFRANG-4008
Adding support for Glue jobs in workflows. They'll look like this
```
States:
start:
End: true
Parameters:
Arguments.$: $.PATH_NAME
Resource: glue:APP_NAME
TimeoutSeconds: 7200
Type: Task
```
This gets transformed into something like
```
States:
start:
End: true
Parameters:
JobName: ENVIRONMENT/NAMESPACE--APP_NAME
Arguments.$: $.PATH_NAME
Resource: arn:aws:states:::glue:startJobRun.sync
TimeoutSeconds: 7200
Type: Task
```
To pass in arguments, you can either specify them explicitly, or to pull them from the path you can do it like above with the `.$/$.` notations
- [Published a new workflow definition in dev](https://us-west-1.console.aws.amazon.com/dynamodb/home?region=us-west-1#tables:selected=workfl …

glue jobs in workflows

---

docs/definitions.md
docs/overview.md
executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go
gen-go/client/client.go
gen-go/models/s_l_state.go
gen-go/models/s_l_state_type.go
gen-js/index.d.ts
gen-js/index.js
gen-js/package.json
handler.go
handler_test.go
package-lock.json
resources/kitchensink.go
resources/workflow_definitions.go
resources/workflow_definitions_test.go
swagger.yml

https://clever.atlassian.net/browse/INFRANG-3783
Allows for creation of workflow definitions with parallel states and submission of those workflows on AWS step functions.  Since parallel states work by having their own state machines on each branch this required adding some recursive calls on state machine validation and expansion of resource values to ARN's.  Verified that this functions as expected and I am able to submit a workflow with a parallel state.
Added test case for parsing parallel states.  Verified via manual ark submission using local workflow-manager that submitting workflows with parallel states works.
Parallel state workflow definition
Map state workflow definition
[Successful parallel state …

Infrang 3783 support for parallel states

---

kvconfig.yml

oncall is getting flooded so I am going to merge this PR

error alerts should go to minor alerts channel not oncall

---

launch/workflow-manager.yml

Removing this deprecated "channel" field. Alarms will instead go to the default channel for your team.
Please confirm that this looks correct, and then merge it

remove alarm channel

---

launch/workflow-manager.yml

pod migration
https://clever.grafana.net/d/application-dashboard/applications?orgId=1&var-environment=production&var-application=workflow-manager&var-pods=All&var-tgMetrics=All&var-albMetrics=All shows no traffic to homepod in prod!
~~- [ ] Update swagger.yml version~~
~~- [ ] Run "make generate"~~
N/A

set to no homepod

---

docs/definitions.md
docs/overview.md
gen-go/client/client.go
gen-go/models/s_l_retrier.go
gen-js/index.js
gen-js/package.json
package-lock.json
swagger.yml

oncall
identity has been using MaxAttempts value > 10 for a while now https://github.com/Clever/ark-config/blob/master/workflows/gcr-sync-pipeline.yml#L105-L113. It turns out this was not actually validated when wfm was on the previous version of wag.
Lets bump this number to 2000. AWS allows `99999999` but that seems like a lot to me so if folks ask we can always bump this again. https://docs.aws.amazon.com/step-functions/latest/dg/concepts-error-handling.html#error-handling-retrying-after-an-error

bump maxattempts to 2000

---

launch/workflow-manager.yml

**Jira:** 
https://clever.atlassian.net/browse/INFRANG-4911
**Overview:**
https://github.com/Clever/catapult/pull/1790 this PR is going to change how deployment are handled for applications after scaling. Today we have a complicated logic which tries to honor the count set by a scale override for apps that are not autoscaled. This logic is hard for infra engineers to remember and prone to bugs.
Because we are not honoring scale anymore, this PR was created to set count = what is currently deployed so that the app doesn't default back to 2. If you think this is not required for your app and the default is fine then feel free to close this PR. Also consider if this app needs autoscaling!

adjust scale to match current scale

---

launch/workflow-manager.yml

https://clever.atlassian.net/browse/INFRANG-4907
- Adds a critical-level alarm to catch higher error volumes for longer.
- Also some small cleanup to launch config - remove unused env vars and set the shepherd to someone currently on the team. See also https://github.com/Clever/ark-config/pull/3856
If you made any changes to swagger.yml - N/A
N/A
N/A

Infrang 4907

---

launch/workflow-manager.yml

Related to FLARE-1317
We are seeing some scalability issues (high latency, workflow update loop falling behind). This is
an attempted quick-fix by adding more CPU and Mem, particularly since the update loop is mostly
parsing and encoding JSON which is pretty CPU intensive.
We could alternately try increasing the number of containers, but I'd like to go this direction
first and see how it goes since the current CPU and Mem values are quite small. Also, on the update
loop side, each container independently reads from the SQS queue with its own little backoff,
retries, sleeping, I am hesistant to just throw more containers as it without trying this first.
If you made any changes to swagger.yml

Add more CPU and Mem

---

launch/workflow-manager.yml

[Discussion here](https://clever.slack.com/archives/CS02Z43PV/p1661980547419559)
Manually scaled to 16, but we want to make sure subsequent deploys also stay at 16 while longer term improvements are being worked on.

Set scale to 16

---

launch/sfn-execution-events-stream.yml

starting to see the consumer fall behind as i turn on event log processing for more workflows

scale up kinesis stream in prod

---

cmd/sfn-execution-events-consumer/main.go

[Link to JIRA](https://clever.atlassian.net/browse/INFRANG-4473)
Fixing a bug where failed workflows aren't showing up in hubble, which searches for resolvedByUser: true.
I'm actually not sure how it used to get set to true for failed workflows. The code changed in this PR diverges from the analogous code in the update loop: https://github.com/Clever/workflow-manager/blob/4cdb21d053b3f2a2035256214bb76c36bfea84d9/executor/workflow_manager_sfn.go#L576-L578

resolved by user should be set for failed workflows

---

store/dynamodb/dynamodb_store.go
store/memory/memory_store.go
store/store.go
store/tests/tests.go

[Link to JIRA](https://clever.atlassian.net/browse/INFRANG-4473)
The AWS support ticket I filed is the best overview:
> Hi,
> We have recently begun using state machine logs to process execution events. We are seeing execution logs getting split across two different log streams, which causes us to process events out of order when these logs are sent to a kinesis log subscription.
> State machine: https://us-west-2.console.aws.amazon.com/states/home?region=us-west-2#/statemachines/view/arn:aws:states:us-west-2:589690932525:stateMachine:production--analytics-p11n-exports-master--1--start
> Example execution: https://us-west-2.console.aws.amazon.com/states/home?region=us-west-2#/executions/details/arn:aws:states:us-west-2:589690932525:execution:production--analytics-p11n-exports-master--1--st …

don't allow updating from terminal to non-terminal state

---

cmd/sfn-execution-events-consumer/main.go

Reverts Clever/workflow-manager#325
The actual problem was event ordering and was solved by https://github.com/Clever/workflow-manager/pull/327

Revert "resolved by user should be set for failed workflows"

---

cmd/sfn-execution-events-consumer/main.go
store/dynamodb/dynamodb_store.go
store/memory/memory_store.go
store/tests/tests.go

There are a bunch of errors causing workflows not to be updated and they are all related to this error. This PR adds additional context so the problem can be debugged more easily.

Add better context to error messages relating to terminal states

---

launch/workflow-manager.yml

**JIRA:** https://clever.atlassian.net/browse/INFRANG-5111
**Overview:**
In this PR we will migrate all internal single region services in this repo to use app mesh to hybrid state.
After this PR is merged the workers will have both envoy proxy sidecar and other appmesh constructs as well as a loadbalancers. Other services/workers have the option to use either option for making connections.
Eventually all services and workers will be restarted to make it so that all traffic comes through envoy at which point we will migrate this service to mesh_only
**Rollout:**
- monitor cpu and memory
- if upstream is in mesh then restart them so that traffic is sent using envoy

migrate single-region services to app mesh in hybrid state in dev

---

launch/workflow-manager.yml

**JIRA:** https://clever.atlassian.net/browse/INFRANG-5113
**Overview:**
In this PR we will migrate all internal single region services in this repo to use app mesh in mesh_only state in DEV only. After this PR is merged the services will delete their loadbalancers. Going forward all the load balancing is done by envoy proxy.
An application in mesh can depend on any other application outside the mesh. But an application outside the mesh cannot depend on an application that is mesh_only.Engineers will still be able to access services using the usual URL but now we are going to share a single loadbalancer across all services!
Currently all apps are in hybrid mode which means that they are already using envoy for loadbalancing instead of using ALBs
**Rollout:**
- monitor cpu and memory …

migrate services to app mesh in mesh_only state in dev

---

launch/workflow-manager.yml

**JIRA:** https://clever.atlassian.net/browse/INFRANG-5115
**Overview:**
In this PR we will migrate all internal single region services in this repo to use app mesh in hybrid state in **PROD**. After this PR the service will have both ALB and envoy proxy. 
When an app is in hybrid mode it's upstream can use either *.int.clever.com url or *.prod.mesh to communicate. On deploy if this app's downstream is in hybrid then we will use *.prod.mesh otherwise we will use *.int.clever.com. Eventually all apps will be restarted so that everthing is using envoy for communication. 
For more details on what each field in `mesh_config` means you can read https://app.getguru.com/card/TnAG64Gc/mesh_config-in-launchyml
Similar to other large scale infrastructure changes we expect some issues so if you …

migrate single region services to app mesh in hybrid state in prod

---

launch/workflow-manager.yml

**JIRA:** https://clever.atlassian.net/browse/INFRANG-5118
**Overview:**
This PR is part of the second cohort of apps that we are migrating from hybrid to mesh_only.
All apps in this cohort are receiving some amount of requests through their ALB which means they pose a higher risk than the previous cohort of apps.
If this app is receiving traffic via the ALB, double check that `setupInternalRoute` is set to true so that routes are setup for lambdas and other clients to access this service once it is mesh_only and ALBs are removed.
If `setupInternalRoute` is not set then check where the requests are coming from before adding it.
https://clever.grafana.net/d/Kyms8kdVz/applications-envoy-alb?orgId=1&from=now-2d&to=now
**Rollout:**
- monitor cpu and memory
- monitor envoy metrics …

migrate services with some alb traffic to mesh_only

---

wfupdater/processevents.go

https://clever.slack.com/archives/C08G6CNMN/p1691612349440029?thread_ts=1691610684.323949&cid=C08G6CNMN
https://clever.slack.com/archives/C05LPSFF1D1/p1691608755911419
Many workflows are not being correctly updated in hubble after succeeding. Multiverse currently has ~38k workflows marked as running, from what I can tell most of them aren't. Each of these workflows seems to match up to a DD log of "unhandled-sfn-event":"ExecutionSucceeded".
In sfn-execution-events-consumer [we handle this event by marking the job status as succeeded. ](https://github.com/Clever/workflow-manager/blob/b9c79d0e5b94f5d3c5c65366fd2b07faabb12be8/cmd/sfn-execution-events-consumer/main.go#L226-L233)
We don't do that [here](https://github.com/Clever/workflow-manager/blob/b9c79d0e5b94f5d3c5c65366fd2b07faabb12be8/wfu …

quick fix attempt

---

main.go

Reverts Clever/workflow-manager#354
This logging wasn't useful and was rolled back. Lets revert it so new merges don't re-enable this.

Revert "Enable aws sdk debug logging"

---

executor/workflow_manager_sfn.go
executor/workflow_manager_sfn_test.go
handler.go

oncall
https://app.datadoghq.com/logs?query=service%3Aworkflow-manager%20env%3Aproduction%20status%3Aerror%20%40status-code%3A500%20&agg_q=%40path&analyticsOptions=%5B%22bars%22%2C%22dog_classic%22%2Cnull%2Cnull%5D&cols=host%2Cservice&index=&messageDisplay=inline&stream_sort=desc&viz=query_table&from_ts=1691877731318&to_ts=1692050531318&live=true
we are seeing a spam of 500s in workflow-manager
Recently we updated hubble to remove a query which was filtering out zombie workflows https://clever.atlassian.net/browse/INFRANG-4733. Looks like now we have some zombie workflows (I haven't investigated why yet) which are now getting queried by hubble leading to this increase in 500s. We should fix the issue that caused these zombie workflows so that the they get deleted from dynamodb but in the …

Oncall fix 500 spam get workflow

---

launch/workflow-manager.yml

https://clever.atlassian.net/browse/INFRANG-5475
In Mesh there is no concept of alarm source of Target, ELB and Total as all metrics are coming from envoy sidecar. We are soon going to merge a change which will block CI for applications if source field is present for InternalErrorAlarms and mesh_config for prod set to mesh_only.
You have to review this PR to see that the new alarms make sense. It was hard to script all the different alarm setups we have across services. In most cases I have removed duplicate alarms but you might want to remove some more alarms or keep some deleted alarms.
Merge PR and deploy via dapple.

clean up alarms

---

store/dynamodb/dynamodb_store.go

In Flare-1520 we saw one workflow retrying indefinitely because the size was too large even without the jobs

Don't retry saving the workflow again if we have already set the jobs to nil

---

launch/sfn-execution-events-consumer.yml

These changes were made manually as part of a flare, and the lambda has since been frozen. This PR encodes the changes into the LC so the service can be deployed normally again.

Increase timeout and batch size

---

launch/workflow-manager.yml

https://clever.atlassian.net/browse/INFRANG-6012
Delete the mesh config as we are exiting mesh and this mesh_config is not used anymore.
Currently catapult is using a feature flag in place of this mesh config and the feature flag is set to "alb_only" for this app. Which means this is already running in production
Merge PR and deploy via dapple

remove mesh_config

---

scripts/workflows-ops/main.go

https://clever.atlassian.net/browse/INFRANG-6114
We need to fetch the workflow history in order to force a status update when running this script with the 'refresh' cmd.
Tested locally. Prior to the fetchHistory change the workflow status was not being updated. After the change, the status was updated.

Worfklow manager ops script: Fetch workflow history to force workflow update

---

executor/sfnconventions/sfnconventions.go
executor/workflow_manager_sfn.go
scripts/backfill-application-tag/README.md
scripts/backfill-application-tag/main.go

[Link to JIRA](https://clever.atlassian.net/browse/INFRANG-5585)
This was broken in a previous refactor related to tags when trying to get the same tags applied to the log group.
Created https://us-west-2.console.aws.amazon.com/states/home?region=us-west-2#/statemachines/view/arn%3Aaws%3Astates%3Aus-west-2%3A589690932525%3AstateMachine%3Aclever-dev--sfncli-test-master--0--echo from local.
For the script, I ran it locally exactly as shown in this PR. It took 38 minutes (for clever-dev, dry run). It took 38 minutes, occasionally printing `sleeping...` so the value for the ticker i chose is in the right ballpark (no sleeps would have meant I could go faster).
(a) Merge
(b) Run the script on `clever-dev` and `production`. (Note this doesn't affect embedded workflow manager, those are already …

Bugfix: add application tag to new state machines correctly

---

scripts/workflows-ops/README.md
scripts/workflows-ops/main.go
scripts/workflows-ops/run-all.sh

[Link to JIRA](https://clever.atlassian.net/browse/INFRANG-6265)
1. Allow setting the rate limit through command line flag and increase the default. I can get up to 100ish (more for short e.g. one-state workflows) on my laptop. But at that scale it will create DB throttling unless the DB is warmed up, so starting with 38 in the default.
2. Wait-ish for workers to be done before exiting.
If you made any changes to swagger.yml: N/A
I ran this stuff for FLARE-1667

Enhancements to workflow-ops scripts
