README.md, data/hello-workflow.post.json, handler.go
Add notes on how to test workflows and an overview of the important packages.
=> Development notes

circle.yml
=> Build all containers

launch/workflow-manager.yml
want to finish this up before deploying to prod
=> use iam roles

resources/jobs.go
absence of this returns a random list of jobs from dynamo.
=> createdTime needs to be set in NewJob()

gen-go/client/client.go, gen-go/client/interface.go, gen-go/client/mock_client.go, gen-go/models/inputs.go, gen-go/models/job.go, gen-go/server/handlers.go, gen-go/server/interface.go, gen-go/server/mock_controller.go, gen-go/server/router.go, gen-js/README.md, gen-js/index.js, gen-js/package.json, handler.go, store/dynamodb/dynamodb_store.go, store/memory/memory_store.go, store/memory/memory_store_test.go, store/store.go, store/tests/tests.go, swagger.yml
JIRA: https://clever.atlassian.net/browse/INFRA-2313
These changes include the createTime enhancement to the job endpoints and the list all workflows from memory store.
=> Infra 2313 workflow api enhancements

gen-go/models/job.go, gen-go/models/task.go, gen-go/models/workflow.go, gen-js/package.json, handler.go, resources/workflows.go, store/dynamodb/dynamodb_store.go, store/memory/memory_store.go, store/tests/tests.go, swagger.yml
- Bug fix CreatedAt for workflows. 
- Add CreatedAt for jobs and tasks. 
- Refactor WorkflowDefinition to include CreateAtTime
=> CreateAt Time fields for workflows, jobs, and tasks

store/dynamodb/dynamodb_store.go, store/dynamodb/dynamodb_store_test.go
First pass GetWorkflows method. It uses a scan operation and filters the result after. It isn't pretty, but for the moment it doesn't require us to make changes to the DB schema.
=> implement GetWorkflows in dynamodb_store

gen-go/client/client.go, gen-go/client/interface.go, gen-go/client/mock_client.go, gen-go/models/inputs.go, gen-go/server/handlers.go, gen-go/server/interface.go, gen-go/server/mock_controller.go, gen-go/server/router.go, gen-js/README.md, gen-js/index.js, gen-js/package.json, handler.go, store/dynamodb/dynamodb_store.go, store/memory/memory_store.go, store/store.go, swagger.yml
Major update to the workflows/{name} endpoint. The endpoint now behaves as follows:
- Returns an array of workflows
- Takes a latest parameter to determine what data to retrieve
- Takes a version parameter iff latest==false
=> update the workflows/{name} endpoint

executor/job_manager.go, swagger.yml
=> change taskName for namespace--app based parsing

executor/job_manager.go, executor/log_helpers.go, kvconfig.yml, resources/jobs.go, resources/tasks.go
this makes it easy for aggregating the status of jobs for all workflows
and for task errors across jobs without the need for excessive
heartbeats.
=> INFRA-2390: also log a numerical value for task/job failures

gen-go/client/client.go, gen-go/client/mock_client.go, gen-go/server/mock_controller.go, gen-js/README.md, gen-js/index.js, gen-js/package.json, glide.lock, glide.yaml, swagger.yml
=> wag to 1.5.2 with circuitBreaker and client-errors

handler.go
https://clever.atlassian.net/browse/INFRA-2475
=> return ordered states from API

resources/workflow_definitions.go, store/dynamodb/dynamodb_store_test.go, store/memory/memory_store_test.go, store/tests/tests.go
https://clever.atlassian.net/browse/INFRA-2483
See commits for details.
=> More cleanup, refactoring

executor/log_helpers.go, executor/log_helpers_test.go, executor/workflow_manager.go, kvconfig.yml
https://clever.atlassian.net/browse/INFRA-2483
Update log text to reflect renames
- job=>workflow
- task=>job
Also updates log routing.
We'll need to modify rules in SFX which depend on this data.  cc @mohit
=> Update log text and routing to reflect renames (job=>workflow, task=>job)

launch/workflow-manager.yml
Seems to be struggling under current (fairly small) load.
Bump up mem and cpu and add autoscaling. Not tied to these numbers - open to change them.
=> Adjust resource limits based on patterns while testing in mp-sfn.

executor/workflow_manager_sfn.go, executor/workflow_manager_sfn_test.go
https://clever.atlassian.net/browse/INFRA-2552
Added some tests, and also manually tested and observed a retry after sending sfncli SIGTERM: https://us-west-2.console.aws.amazon.com/states/home?region=us-west-2#/executions/details/arn:aws:states:us-west-2:589690932525:execution:raf--cil-reliability-dashboard-master--4--start:6a7d6918-4d97-475f-b626-52a4723cbfc1
=> retry on sfncli.CommandTerminated

executor/workflow_manager_sfn.go
* Change `case sfn.HistoryEventTypeExecutionFailed` to check for `details != nil`
* Capture errors in `case sfn.HistoryEventTypeExecutionFailed` and write it to job.StatusReason. 
* use `aws.___Value` functions where possible since they do a `nil` check. 
=> use aws deference functions in execution history

circle.yml
=> deploy to dev-infra since that's the right place

executor/workflow_manager_sfn.go
Similar to what we're doing for activity failues. Keeping it consistent so that we don't overwrite job the failure reason with the longer version when we encounter an execution failure event.
=> Trim the statusReason down to last 3 lines for execution-level failures.

executor/workflow_manager_sfn.go, executor/workflow_manager_sfn_test.go, gen-go/models/workflow.go, gen-js/package.json, swagger.yml
Thanks @rgarcia, for the perfect TODO to ease this task :)
- [ x ] Update swagger.yml version
- [ x ] Run "make generate"
=> add output from sfn

executor/workflow_manager_sfn.go, executor/workflow_manager_sfn_test.go
We allow Cancellation of Failed Workflows. However in the current implementation this only worked while SFN kept the execution ID in history.
If a Workflow is complete, we should allow marking a Workflow as Cancelled.
The logic here is a bit confusing but simple, any ideas on how to write it better welcome. 
- [ NA ] Update swagger.yml version
- [ NA ] Run "make generate"
=> cancellation of failed workflows

executor/log_helpers.go, executor/log_helpers_test.go, executor/workflow_manager.go, kvconfig.yml
https://clever.atlassian.net/browse/INFRA-2620
Added a test, also ran locally and submitted some workflows
```
Thu 01:37:57.377 workflow-manager/local> { source.title=workflow-manager.pending-workflows-locked, deploy_env:"raf", id:"8f065794-f26c-49be-923f-bd0f69c80a08", update-loop-lag-seconds:2 }->[update-loop-lag-alert]
```
=> log update loop lag

executor/log_helpers.go, executor/log_helpers_test.go, kvconfig.yml, main.go
make the routing here consistent with https://github.com/Clever/ecs-metrics/pull/43
=> tweak count metrics

store/dynamodb/dynamodb_store.go, store/dynamodb/dynamodb_store_test.go, store/dynamodb/workflow.go
https://clever.atlassian.net/browse/INFRA-2585
=> add 1 month ttl to workflows dynamo table

docs/overview.md, gen-js/package.json, swagger.yml
Let's bump it after all to make deps better. :sigh:
=> Bump version.

circle.yml
=> deploy without confirm in dev-infra and clever-dev

executor/workflow_manager.go
The concurrent approach allowed us to do many updates in parallel, but
we don't need this performance optimization. Instead, our priority is
to prevent the polling loop from causing too many DB writes, leading to
throttling.
Previously, 10 workflows were concurrently being updated, and each of
those updates was internally doing retries via aws-sdk-go library.  With
this change, we'll now backoff immediately the first time the polling
loop sees a throttled error. Ideally, this should result in up to 10x less
throttled writes.
More on AWS SDK Go retry configuration:
https://github.com/aws/aws-sdk-go/blob/952498f4a390118ac65ad59cbe0c8b57ed69b6b5/aws/client/client.go#L58-L64
=> simplify backoff; remove concurrrency from poll/update loop

Gopkg.lock, Gopkg.toml, Makefile, golang.mk, handler.go, handler_test.go
=> convert '' to {} in startWorkflow input

executor/workflow_manager_sfn.go
=> adding update loop for this workflow

executor/workflow_manager_sfn_test.go
Previously we had no test coverage here.
This also helps us ensure that the SQS message submission we missed in
RetryWorkflow has a regression test.
https://github.com/Clever/workflow-manager/pull/136
=> add unit test for RetryWorkflow

Gopkg.lock, Makefile, docs/overview.md, executor/workflow_manager_sfn.go, executor/workflow_manager_sfn_test.go, gen-go/models/new_workflow_definition_request.go, gen-go/models/workflow_definition.go, gen-js/package.json, handler.go, resources/kitchensink.go, resources/workflow_definitions.go, resources/workflow_definitions_test.go, swagger.yml
Added DefaultTags to NewWorkflowDefinitionRequest and WorkflowDefinition
Testing: see added tests. ```make test``` runs cleanly
=> Infra 2881 team tagging

handler.go, kvconfig.yml
If jobs are being dropped on the floor, we should know about it
Jira: https://clever.atlassian.net/browse/INFRA-3274
=> Send notification to #oncall-infra if an unknown workflow is started

executor/workflow_manager_sfn.go
See line 29 in changed file.
N/A - [ ] Update swagger.yml version
N/A - [ ] Run "make generate"
=> Fixed typo where comment and code were out of sync

Gopkg.lock, executor/workflow_manager.go
These shouldn't be necessary. But note that `Gopkg.lock` did change.
=> Changing update frequency to every 60 seconds instead of 30

main.go
=> Reduce retries to 2

embedded/embedded.go, embedded/embedded_test.go, embedded/notsupported.go, embedded/poll.go
this will let programs create workflow definitions at runtime, in
addition to the wfdefs loaded on startup
=> embedded: add support for NewWorkflowDefinition

Gopkg.lock, Gopkg.toml, Makefile, executor/workflow_manager.go, executor/workflow_manager_test.go
=> Requeues done workflows if UpdateWorkflow fails

docs/overview.md, gen-go/server/db/dynamodb/dynamodb.go, gen-go/server/db/dynamodb/workflowdefinition.go, gen-js/package.json, swagger.yml
=> Looks like MaxAttempts was defined twice

embedded/embedded.go, embedded/embedded_test.go
Some sane defaults since we are starting to use this in more places
=> Embedded Workflow Defintion validation

Gopkg.lock, Gopkg.toml, gen-go/client/mock_client.go, gen-go/server/db/dynamodb/dynamodb-local.sh, gen-go/server/db/dynamodb/dynamodb.go, gen-go/server/db/dynamodb/dynamodb_test.go, gen-go/server/db/dynamodb/workflowdefinition.go, gen-go/server/db/interface.go, gen-go/server/db/tests/tests.go, gen-go/server/mock_controller.go
=> update gomock dependency version

gen-js/package.json, swagger.yml
for https://github.com/Clever/workflow-manager/pull/173
=> 0.9.6 patch version bump

executor/workflow_manager_sfn.go
This change fixes a bug introduced when we did some refactoring here https://github.com/Clever/workflow-manager/pull/171/commits/ad8e0be85ca39a25acd9189a74a197f576261120. The map `eventIDToJob` was declared outside of a function and we tried to declare it inside of the function where it was used, however the function `GetExecutionHistoryPagesWithContext` can be called multiple times and it needs to have a reference to the same map to be able to group every set of related events into a single Job. 
@meliaj  noticed that some workflows are showing that one of the states is queued when the workflow has completed successfully. We also saw some of these logs https://github.com/Clever/workflow-manager/blob/47b1b785fdd4d52cce5c2ea930201a68f12fb555/executor/workflow_manager_sfn.go#L542
The bug …
=> fix event ID to jobs map scoping

Gopkg.lock, Gopkg.toml, embedded/embedded.go, embedded/embedded_test.go, embedded/notsupported.go, embedded/poll.go, embedded/sfnfunction/sfnfunction.go
this will make errors easier to debug
=> embedded: use xerrors

Gopkg.lock, Gopkg.toml, executor/log_helpers.go, executor/log_helpers_test.go, main.go
see https://github.com/Clever/aws-sdk-go-counter/pull/2
=> use new counter lib

docs/definitions.md, docs/overview.md, embedded/embedded.go, gen-go/models/s_l_state.go, gen-js/package.json, swagger.yml
=> Parallel branches support for Embedded WFM

Gopkg.lock, docs/overview.md, gen-go/server/db/dynamodb/dynamodb.go, gen-go/server/db/dynamodb/workflowdefinition.go, gen-go/server/handlers.go, gen-go/server/middleware.go, gen-go/server/router.go, gen-js/package.json, main.go, package-lock.json, swagger.yml
=> INFRA-3446: bump retries

executor/workflow_manager_sfn.go
https://clever.atlassian.net/browse/INFRA-3602
Tagging has made it easier to build out the multi-pod grafana dashboard for ECS and ALB resources, since via the GetResources API we can easily pull in all AWS resources associated with things like environment, application and pod.
We should do the same for step functions resources so we can pull those metrics into grafana.
There are also benefits to tagging when it comes to cost attribution.
=> tag state machines on creation

executor/workflow_manager_sfn.go, kvconfig.yml
https://clever.atlassian.net/browse/INFRA-3435
=> add metric for failed workflows with dimension for failing job

executor/sfncache/sfn.go, executor/sfncache/sfn_test.go
=> Add context to cached sfnapi

store/dynamodb/dynamodb_store.go
This change adds paging to the `GetWorkflowDefinitions` call.
Tested locally via: 
`curl http://localhost:8080/workflow-definitions`
No changes to swagger so not checking the boxes below:
=> Use paging to get all workflow definitions

docs/overview.md, gen-js/package.json, store/dynamodb/dynamodb_store.go, swagger.yml
=> use new 'lastEvaluatedKey'

Gopkg.lock, docs/overview.md, gen-go/client/client.go, gen-go/server/db/dynamodb/dynamodb_test.go, gen-go/server/handlers.go, gen-go/server/middleware.go, gen-go/server/router.go, gen-js/README.md, gen-js/index.d.ts, gen-js/index.js, gen-js/package.json, package-lock.json, swagger.yml, wag.mk
=> Re-gen with latest wag

docs/overview.md, embedded/embedded.go, embedded/embedded_test.go, gen-go/client/client.go, gen-go/client/doer.go, gen-js/index.js, gen-js/package.json, swagger.yml
Support Map state in embedded. We previously added support for them in non-embedded, but I want them in embedded, too.
If you made any changes to swagger.yml: 
I didn't, but I want to make a new release of `embedded`, so I'm still bumping version.
I ran to completion an embedded workflow using this! 
N/A
=> Embedded map

docs/overview.md, gen-go/client/client.go, gen-js/index.js, gen-js/package.json, swagger.yml
Forgot to bump version in #303 
=> Version bump.

launch/workflow-manager.yml
**JIRA:** [INFRANG-4688](https://clever.atlassian.net/browse/INFRANG-4688)
This is now required
=> metrics exporters now required

executor/sfnconventions/sfnconventions.go, executor/workflow_manager_sfn.go
[Link to JIRA](https://clever.atlassian.net/browse/INFRANG-4473)
Follow up bugfix to previous PR
=> fix log group name to fit AWS conventions

cmd/sfn-execution-events-consumer/main.go, store/dynamodb/dynamodb_store.go, store/memory/memory_store.go, store/store.go
[Link to JIRA](https://clever.atlassian.net/browse/INFRANG-4473)
Bugfix for failed jobs not showing up in Hubble. I mistakenly did not update the last job field in porting this logic over from the update loop.
=> correctly set last job field

cmd/sfn-execution-events-consumer/main.go
[INFRANG-5061](https://clever.atlassian.net/browse/INFRANG-5061)
This is a quick and dirty mitigation to try and get Hubble into a better state. Currently the lambda is failing where we don't handle the out of order state error causing most records not to get processed. Root cause is still TBD, but hopefully this will mean most workflows can get marked as succeeded in Hubble again.
=> INFRANG-5061 - Add error mitigations in both cases where we call update attributes

cmd/sfn-execution-events-consumer/main.go, scripts/force_refresh_workflows.go
[INFRANG-5061](https://clever.atlassian.net/browse/INFRANG-5061)
This PR adds a script to force updates on workflows in a stuck state. Stuck state may occur when the SFN state pipeline has bugs and loses data. 
Additionally, I have added notes about the special case handling of event ID 2.
=> INFRANG-5061 - Fix case handling workflow running state

.circleci/config.yml, gen-go/client/client.go, gen-go/client/doer.go, gen-go/client/go.mod, gen-go/client/interface.go, gen-go/server/db/dynamodb/workflowdefinition.go, gen-go/server/db/tests/tests.go, go.sum, package-lock.json
[Link to JIRA](https://clever.atlassian.net/browse/INFRANG-5132)
Bumping wag deps, simplifying submods go.mod files, adding in circle-ci tagging, ver bump
make test
=> latest wag fixes

launch/workflow-manager.yml
Reverts Clever/workflow-manager#336
We have hit a limit on number of gateway routes so lets revert for now
=> Revert "migrate single-region services to app mesh in hybrid state in dev"

cmd/sfn-execution-events-consumer/main.go
[INFRANG-5061](https://clever.atlassian.net/browse/INFRANG-5061)
This PR fixes 2 bugs. 
1. Handle the case where event ID number 2 may be a terminal event. I don't know for sure that this case exists but it's an easy change and doesn't make the code flow more messy.
2. Don't fail and throw out all unprocessed data on any error. I haven't dug in, but I suspect this may be ay least one source of our data loss. Given that this change was easy I wanted to try it out and see if I can save time on really digging into why this is occurring.
These aren't random shots in the dark, more like educated guesses. My hope is this 20min spent throwing together this PR fixing at least one bug that certainly exists will save me a few hours of debugging.
=> Fix data loss

launch/workflow-manager.yml
Reverts Clever/workflow-manager#337
Forgot to revert the revert!
=> Revert "Revert "migrate single-region services to app mesh in hybrid state in dev""

launch/workflow-manager.yml
=> wfm is used by ark and others so setupInternalRoute

launch/workflow-manager.yml
https://clever.slack.com/archives/C08G6CNMN/p1677284245364229
=> Roll back to hybrid temporarily to fix deploys

launch/workflow-manager.yml
Reverts Clever/workflow-manager#347
=> Revert "Roll back to hybrid temporarily to fix deploys"

main.go
=> Enable aws sdk debug logging

cmd/sfn-execution-events-consumer/main.go, main.go
Reverts Clever/workflow-manager#353
=> Revert "Turn off retries for dynamo db"

main.go
There was some bad interaction between aws sdk's retry mechanism, the way AWS requests are cryptographically signed by AWS credentials, and the way that the otelhttp instrumentation modified outgoing requests. I'm not sure the details. But in out-of-repo experiments, removing the propagator fixes it. And since the AWS services are discarding these headers anyway, there's no reason to send them.
I kept the trace headers going to elasticsearch at the cost of having tracedTransport take an extra arg since maybe that's useful; I think ES and/or OpenSearch has some kind of OTel support?
[Link to JIRA](https://clever.atlassian.net/browse/INFRANG-5276)
[insert description]
=> Fix retries with AWS SDK.

handler.go
[Link to JIRA](https://clever.atlassian.net/browse/FLARE-1520)
=> Temp Fix - Comment out UpdateWorkflowHistory so we can clear out stuck large jobs

executor/workflow_manager_sfn.go
https://clever.atlassian.net/browse/INFRANG-5519
This PR updates the create workflow handler to clean up orphaned workflows in a goroutine. Previously, this was done synchronously with a shared context, and if the workflow failed due to a timeout, then the cleanup would also fail.
=> INFRANG-5519 - Prevent zombie workflows

.circleci/config.yml
This upgrades CircleCI config yamls to use 
`context: aws*` definitions. See https://clever.slack.com/archives/C063L91T7/p1695056411674719 for the announcement.
If the CI checks are green, it means it is working. PLEASE APPROVE AND MERGE THIS, if it is all good!
There might be a whitespace that is created due to loading yaml into memory, processing, and writing back to file. 
You can use "Ignore white space in code review" toggle in Github PR view to simplify the code review: https://github.blog/2018-05-01-ignore-white-space-in-code-review/, which would add `?diff=unified&w=1` to the PR url.
=> Update CI to use context

Makefile, cmd/sfn-execution-events-consumer/main.go, launch/sfn-execution-events-consumer.yml, launch/workflow-manager.yml
https://clever.atlassian.net/browse/INFRANG-6284
Fixes the bug causing errors not to be bubbled up
Tested by running the lambda locally
=> [INFRANG-6284] Fix unpropegated errors in sfn-execution-events-consumer

cmd/sfn-execution-events-consumer/main.go, go.mod, go.sum, main.go
[Link to JIRA](https://clever.atlassian.net/browse/INFRANG-6559)
* Follow up to https://github.com/Clever/workflow-manager/pull/388
* Add required `TableName` field for generated dynamodb clients
- [n.a] Update swagger.yml version
- [n.a] Run "make generate"
* Deployed both w-f-m and lambda to dev
=> add tablename
